### ISSUE TITLE
organization name

### ISSUE THREAD

**Issue by carlwgeorge** [iuscommunity/infrastructure#11]
Right now the [IUS project](https://ius.io) has two GitHub organizations, @iuscommunity-pkg for package sources and @iuscommunity for everything else.  I'd like to consolidate these into a single repo with a shorter name.  I created @iusrepo while experimenting with drone, so that is one option to use.  I would prefer to use the name "ius", but unfortunately that name is already taken.

@ius I know it's a long shot, but is there any chance you'd be willing to give up your username so I can create an organization by that name?  GitHub makes it easy to change your username, and automatically redirects references to your existing repos.  I'd be happy to mail you some stickers from the project for your trouble.

- https://help.github.com/articles/changing-your-github-username/
- https://help.github.com/articles/what-happens-when-i-change-my-username/

**Comment by ius** [comment]
This has been requested before. While I definitely understand why you'd like to use the name, I'm not willing to part ways with it. I'm sorry.

**Comment by carlwgeorge** [comment]
Thanks anyways.

**Comment by carlwgeorge** [comment]
@iusrepo is the new organization.  I'm transferring package source repositories there as I update them.
