### ISSUE TITLE
Errata for IUS packages

### ISSUE THREAD

**Issue by MarkRWatts** [iuscommunity/infrastructure#12]
How feasible is it for IUS to publish updates with appropriate Errata metadata to group packages?

We import IUS into a Satellite server, and our patching is primarily based on applying Errata.
Naturally IUS packages don't get applied since they're not grouped as Errata.

It would be very useful if this were the case.

**Comment by carlwgeorge** [comment]
I wouldn't even know where to start.  Do you have any reference documentation on how to create Satellite-compatible errata metadata?

**Comment by MarkRWatts** [comment]
I'd naively assumed there would be a similar script to createrepo, for creating Errata. My Google-fu is weak here and I've not really turned one up.

But, errata are defined by the contents of the updateinfo.xml contained in the same folder as the repository metadata. I can't find a formal definition for this file, but they're human readable - the EPEL one makes some sense to me so perhaps that can be used as a basis?
https://www.mirrorservice.org/sites/dl.fedoraproject.org/pub/epel/7/x86_64/repodata/

The closest description I can find is at the bottom of this page: https://docs.pulpproject.org/en/2.16/plugins/pulp_rpm/tech-reference/rpm.html?highlight=errata#

**Comment by carlwgeorge** [comment]
The IUS project has reached it's end of life, and will not be addressing any more issues or pull requests.

ius.io/faq#why-doesnt-ius-have-packages-for-rhel-8

iusrepo/announce#41
