### ISSUE TITLE
IUS CDN

### ISSUE THREAD

**Issue by carlwgeorge** [iuscommunity/infrastructure#14]
# Summary

The IUS project will be migrating from our existing mirror network to utilizing [Rackspace CDN](https://www.rackspace.com/en-us/cloud/cdn-content-delivery-network).

# Current State

Currently the IUS repositories are published to https://dl.iuscommunity.org.  We have a network of community mirrors that replicate this content.  The ius-release package points users to https://mirrors.iuscommunity.org/mirrorlist, which provides a geographically sorted list of mirrors based on the GeoIP information of the requesting IP.

# Future State

https://repo.ius.io has been configured using [Rackspace CDN](https://www.rackspace.com/en-us/cloud/cdn-content-delivery-network).  New packages will be published here going forward.  Existing packages on https://dl.iuscommunity.org will continue to be updated until the transition is complete.  This will be accomplished by updating the ius-release package to point to https://repo.ius.io instead of https://mirrors.iuscommunity.org/mirrorlist.  Users of the ius-release package should not have to take any action other than upgrading ius-release.  If you have customized the repo files from this package, you will need to merge in the rpmnew files just like any other package update.

# FAQ

### Can I start using the CDN now?

Sure!  If you are already subscribed to IUS, ~~you can update the ius-release package from the testing repo~~ just update ius-release.  Make sure to clear the yum cache afterwards.

```
yum update ius-release
yum clean all
```

On a system that isn't subscribed to IUS yet, new ius-release packages can be downloaded at these links:

* https://repo.ius.io/ius-release-el6.rpm
* https://repo.ius.io/ius-release-el7.rpm

You can also download the repo config and GPG key individually from https://repo.ius.io.

### What if I still want to mirror IUS for my own needs?

We realize that many members of our mirror network still would like to mirror our content for their own needs, commonly referred to as a "private" mirror.  This will still be an option even after https://dl.iuscommunity.org is taken offline in the future.  We will be reaching out to existing mirror contacts with the new rsync information.  If anyone new wants to mirror IUS for their own needs reach out to dev@ius.io.

### Why don't I see separate packages for RHEL and CentOS?

In the past IUS built separate packages for RHEL and CentOS due to possible long delays between a RHEL release and CentOS catching up.  Now that Red Hat sponsors CentOS that only takes a few weeks at most. It's just not worth the effort of the duplicate builds anymore.  In the future, if a library change happens in RHEL that causes a built package to be compatible with the new RHEL but not the yet-to-catch-up CentOS, IUS can keep that package in ius-testing until CentOS catches up. This is the approach that EPEL normally takes.

**Comment by devicenull** [comment]
Why are you switching away from third party mirrors?

**Comment by carlwgeorge** [comment]
@devicenull Managing a mirror network takes much more effort than using a CDN.  On top of that, CDN solves the distribution problem much better.  There are more endpoints around the globe, and no work is needed from the IUS team as the CDN service adds and removes nodes.  Anyone that still wants to mirror IUS can, but the official ius-release package is going to point to the CDN.

**Comment by jjlin** [comment]
@carlwgeorge For people who run "private" mirrors, could you just post the rsync info publicly?

**Comment by carlwgeorge** [comment]
@jjlin The domain for the rsync is the same as the https origin for the CDN.  I'd like to avoid users bypassing the CDN.  If you need the rsync info just email dev@ius.io and I'll be happy to share it with you.

**Comment by carlwgeorge** [comment]
I've created a new [ius-release](https://github.com/iusrepo/ius-release) package that points to the CDN.  It can be downloaded at the following links for those that want to start using it.

* https://repo.ius.io/ius-release-el6.rpm
* https://repo.ius.io/ius-release-el7.rpm

I have not published this package into the stable repo yet.

**Comment by kustodian** [comment]
What about the CentOS packages? I only see EL. Old repository URL has separate repositories for CentOS and RHEL.

**Comment by carlwgeorge** [comment]
@kustodian Yes, in the past IUS built separately for RHEL and CentOS.  To my knowledge we were the only third party repository doing this.  Even EPEL only builds against RHEL.  In the past there were concerns with long delays between a RHEL release and CentOS catching up, but now that Red Hat sponsors CentOS that only takes a few weeks at most.  It's just not worth the effort of the duplicate builds anymore.

In the future, if a library change happens in RHEL that causes a built package to be compatible with the new RHEL but not the yet-to-catch-up CentOS, IUS can keep that package in ius-testing until CentOS catches up.  This is the approach that EPEL normally takes.

**Comment by kustodian** [comment]
Cool. That means that we can safely switch to the new repo URL. Thanks.

**Comment by kustodian** [comment]
Is the new repo up-to-date? Because once I changed the URL yum is telling me that the repo data is older from what we already have:
```
ius                                                                                                                                                                                  | 1.3 kB  00:00:00     
Not using downloaded ius/repomd.xml because it is older than what we have:
  Current   : Wed May  1 10:58:04 2019
  Downloaded: Mon Apr 22 18:45:24 2019
```

**Comment by carlwgeorge** [comment]
Yes, it's up to date.  That was just a side effect of the timing of migrating the content.  The old system regenerated the repodata every night, even if the content was the same, and that ran a few more times after I seeded the new repo with the old content.  A `yum clean all` would resolve this for you.  I went ahead and regenerated the repodata for good measure as well.

**Comment by kustodian** [comment]
Thanks for the explanation.

**Comment by amwestg** [comment]
https://repo.ius.io/6/i386/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Need update for PHP71u for i386 - directory missing

**Comment by carlwgeorge** [comment]
As part of this infrastructure refresh, we now build our packages in [Cirrus CI](https://cirrus-ci.org).  Due to the **extremely** low usage of our i686 packages, we made this switch without a plan for building i686 packages in the future.  If you would like to help re-enable building those, take a look at our [build configuration](https://github.com/iusrepo/php71u/blob/master/.cirrus.yml) and the [Cirrus CI docs](https://cirrus-ci.org/guide/writing-tasks/) and send a pull request.  Considering that the Cirrus infrastructure is x86_64 only, some cross compile solution will be needed to create i686 packages.

Personally, I think the effort that would be needed for this would be better spent migrating your systems to RHEL/CentOS 7 x86_64.  RHEL/CentOS 6 only has 17 months until it's [end of life date](https://access.redhat.com/support/policy/updates/errata#Life_Cycle_Dates).  It's also already in [Maintenance Support 2 Phase](https://access.redhat.com/support/policy/updates/errata#Maintenance_Support_2_Phase), meaning that only the most critical and urgent fixes are backported, entirely at Red Hat's discretion.  EL6 is on life support.

**Comment by amwestg** [comment]
> 
> 
> As part of this infrastructure refresh, we now build our packages in [Cirrus CI](https://cirrus-ci.org). Due to the **extremely** low usage of our i686 packages, we made this switch without a plan for building i686 packages in the future. If you would like to help re-enable building those, take a look at our [build configuration](https://github.com/iusrepo/php71u/blob/master/.cirrus.yml) and the [Cirrus CI docs](https://cirrus-ci.org/guide/writing-tasks/) and send a pull request. Considering that the Cirrus infrastructure is x86_64 only, some cross compile solution will be needed to create i686 packages.
> 
> Personally, I think the effort that would be needed for this would be better spent migrating your systems to RHEL/CentOS 7 x86_64. RHEL/CentOS 6 only has 17 months until it's [end of life date](https://access.redhat.com/support/policy/updates/errata#Life_Cycle_Dates). It's also already in [Maintenance Support 2 Phase](https://access.redhat.com/support/policy/updates/errata#Maintenance_Support_2_Phase), meaning that only the most critical and urgent fixes are backported, entirely at Red Hat's discretion. EL6 is on life support.

Thanks for the reply. We would appreciate if the current I386 packages for CentOS 6 are either saved or moved to your new CDN while we transition this server to CentOS 8 when it's ready later this year..  I may download the existing PHP71u packages to my local repo if it comes to that.

Any plans on building packages for RHEL 8/CentOS 8?

**Comment by carlwgeorge** [comment]
> We would appreciate if the current I386 packages for CentOS 6 are either saved or moved to your new CDN while we transition this server to CentOS 8 when it's ready later this year.

All of the previous i686 packages are available on the CDN in the [archive repository](https://repo.ius.io/archive/6/i686/).  With the ius-release package installed they can be accessed by adding the `--enablerepo ius-archive` flag to yum.  We keep all our old builds in the archive, so it shouldn't be necessary to mirror them yourself unless you really want to.

> Any plans on building packages for RHEL 8/CentOS 8?

Not at this time.  I've gone into more detail [here](https://github.com/iusrepo/packaging/issues/6).

**Comment by ScoobyDone** [comment]
are the verbiage and links at https://ius.io/GettingStarted/ going to be replaced?
> IUS compiles separate packages 
> {rhel,centos}{6,7}.iuscommunity.org replaced by repo.ius.io

**Comment by carlwgeorge** [comment]
@ScoobyDone Yes, the website is getting overhauled and the update will include refreshed information for getting started.

**Comment by khambrecht** [comment]
> All of the previous i686 packages are available on the CDN in the [archive repository](https://repo.ius.io/archive/6/i686/). With they ius-release package installed they can be accessed by adding the `--enablerepo ius-archive` flag to yum. We keep all our old builds in the archive, so it shouldn't be necessary to mirror them yourself unless you really want to.

looks like the i686 package are gone. Any chance to get them back?

**Comment by carlwgeorge** [comment]
@khambrecht See [this comment](https://github.com/iusrepo/infrastructure/issues/14#issuecomment-507051198) about i686 packages.  The previously built i686 packages are still available from the old URL: https://dl.iuscommunity.org/pub/ius/

**Comment by khambrecht** [comment]
@carlwgeorge thanks

iirc, the i686 packages have been available via https://repo.ius.io/archive/6/i686/ also. At least a couple of weeks ago.

But I'll switch over to https://dl.iuscommunity.org/pub/ius/ then.

**Comment by carlwgeorge** [comment]
The legacy [mirrorlist API](https://mirrors.iuscommunity.org/mirrorlist) will be turned off 2020-01-08.

**Comment by BBQigniter** [comment]
this info, that iuscommunity.org-repo is being "turned off" and that https://dl.iuscommunity.org/pub/ius/stable/ will not be updated soon, would be super great somehwere in the ius-faq (with mentioning "iuscommunity.org") or so. i couldn't find any info on ius.io in the FAQ or in About - just that there was/will be some change.

because me and my colleagues now wondered why we do not get the latest php72u-common 7.2.24 packages on our internal mirror and with some googleing i found this github issue with the explanation :)

**Comment by carlwgeorge** [comment]
@BBQigniter The [website sources](https://github.com/iusrepo/iusrepo.github.io) are linked in the website footer.  If you'd like to add an FAQ item or update an existing one, please send a pull request.

**Comment by dpeterson1128** [comment]
I appreciate the info. Same as @BBQigniter I am needing the php72u-common 7.2.24 package but it is not on the old mirror (https://dl.iuscommunity.org/pub/ius/stable/). Is there a new rysnc target I can point to for https://repo.ius.io/? 

This is the rsync target I was previously using that no longer works: rsync://dl.iuscommunity.org/ius/stable/CentOS/7/x86_64/

**Comment by carlwgeorge** [comment]
@dpeterson1128 Assuming you're the same David that emailed me, I've replied to the email with instructions.

**Comment by carlwgeorge** [comment]
As promised in https://github.com/iusrepo/infrastructure/issues/14#issuecomment-543350448, I have turned off the mirrorlist service.  If your system wasn't able to update ius-release from the repos before now, you should take the following steps.

1. `yum erase ius-release`
2. `rm /etc/yum.repos.d/ius*.repo*`
3. follow the instructions on https://ius.io/setup

**Comment by laidbackpeter** [comment]
I am still facing some issues with this package python36-mod_wsgi despite following the instructions. This is the output I am getting `No package matching 'python36-mod_wsgi' found available, installed or updated.` However python36u-mod_wsgi is still available.

Here is the output for yum repolist:

```
Loaded plugins: fastestmirror, priorities, s3iam
Loading mirror speeds from cached hostfile
 * base: ftp.heanet.ie
 * epel: mirrors.coreix.net
 * extras: ftp.heanet.ie
 * updates: ftp.heanet.ie
https://repo.ius.io/ius-release-el7.rpm/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article 

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

repo id                                               repo name                                                                    status
base                                                  CentOS 7 - base                                                              10,097
epel                                                  Extra Packages for Enterprise Linux 7 - x86_64                               13,509
extras                                                CentOS 7 - extras                                                               307
ius                                                   IUS YUM repo                                                                    570
kmod-ena                                              AWS ENA kernel module, built by The Scale Factory                                 1
kmod-ixgbevf                                          Intel ixgbevf kernel module, built by The Scale Factory                           2
mysql-connectors-community/x86_64                     MySQL Connectors Community                                                      141
mysql-tools-community/x86_64                          MySQL Tools Community                                                           105
mysql57-community/x86_64                              MySQL 5.7 Community Server                                                      404
puppet-omnibus                                        Scale Factory Puppet omnibus packages                                            40
sclo                                                  Software Collections.org: 7 - sclo                                            8,770
updates                                               CentOS 7 - updates                                                            1,010
yum-s3-iam                                            S3-IAM plugin for yum, built by The Scale Factory                                 3
repolist: 34,959
```

and here is the output for the python I am using:

```
Loaded plugins: fastestmirror, priorities, s3iam
Loading mirror speeds from cached hostfile
 * base: ftp.heanet.ie
 * epel: mirrors.coreix.net
 * extras: ftp.heanet.ie
 * updates: ftp.heanet.ie
https://repo.ius.io/ius-release-el7.rpm/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article 

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

Available Packages
Name        : python3
Arch        : i686
Version     : 3.6.8
Release     : 10.el7
Size        : 69 k
Repo        : base
Summary     : Interpreter of the Python programming language
URL         : https://www.python.org/
License     : Python
```


Any idea what I am could missing? cc @carlwgeorge

**Comment by mty22** [comment]
@carlwgeorge Congrats on moving to Rackspace CDN. :)

Just a question, did you plan on reaching out to existing mirror admins to advise? 

I have been the maintainer for ius.mirror.digitalpacific.com.au for almost 5 years now and I only happened to stumble on this thread by chance as I noticed our IUS mirror was out of sync as I was migrating all mirrors to newer hardware.

Just as a note, we still see a lot of traffic from existing IUS users who are yet to update their repo files. It may be worth updating your rsync end point, more specifically rsync://dl.iuscommunity.org/ius/ to just be a 301 to new newer CDN? (lets us maintainers recover resources).

**Comment by carlwgeorge** [comment]
@mty22 I sent you (and all the other mirror contacts we had on file) an email the same day I opened this issue (2019-04-30).  

Anyone syncing from rsync://dl.iuscommunity.org/ius/ is getting the latest content set.  That hostname will eventually go away.  If you'd like to continue to mirror IUS for your own needs reach out to dev@ius.io for the new hostname.

**Comment by antwal** [comment]
> As promised in [#14 (comment)](https://github.com/iusrepo/infrastructure/issues/14#issuecomment-543350448), I have turned off the mirrorlist service. If your system wasn't able to update ius-release from the repos before now, you should take the following steps.
> 
> 1. `yum erase ius-release`
> 2. `rm /etc/yum.repos.d/ius*.repo*`
> 3. follow the instructions on https://ius.io/setup

Not working

https://extras.getpagespeed.com/redhat/6/noarch/repodata/repomd.xml: [Errno -1] Error importing repomd.xml for getpagespeed-extras-noarch: Damaged repomd.xml file
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: getpagespeed-extras-noarch. Please verify its path and try again

**Comment by carlwgeorge** [comment]
@antwal I have no idea what getpagespeed is, but this isn't the place to report issues for it.

**Comment by carlwgeorge** [comment]
This issue is closed, but seems to be a magnet for unrelated problems.  To avoid continuing sending notification to users that subscribed for the CDN changes, I'm going to lock this issue.  Please follow the [instructions in our FAQ](https://ius.io/faq#how-can-i-report-an-issue-with-an-ius-package) for future problems.
