### ISSUE TITLE
Broken links to RHEL packages

### ISSUE THREAD

**Issue by mikeweinberg** [iuscommunity/infrastructure#15]
The links to RHEL packages here are broken: [https://ius.io/Packages/](https://ius.io/Packages/)

**Comment by carlwgeorge** [comment]
Thanks for the heads up.  I'm working on migrating the site to GitHub pages, I'll fix this when I do that.

**Comment by carlwgeorge** [comment]
We don't generate repoviews anymore.  The new site doesn't attempt to list the packages, but rather links to our GitHub repos with the "rpm" topic.

https://github.com/iusrepo/iusrepo.github.io/blob/fbc8a5cfac396bee31a148d3ab1e40907af70d89/_includes/header.html#L29-L32
