### ISSUE TITLE
GPG key error in syncing IUS CDN repo

### ISSUE THREAD

**Issue by philtech-oh** [iuscommunity/infrastructure#17]
I maintain a private repo host for internal company use, using the yum utility `reposync` to download the CentOS and other repos we normally use.  When attempting to use the IUS CDN repo, I get a GPG key error and an unsuccessful download, with every downloaded package immediately deleted.

The reposync command is this:
`reposync -g -l -p /var/repo/ius/7/x86_64 --norepopath -m --download-metadata -r ius`
The result is this:
`Loading "fastestmirror" plugin
Loading "langpacks" plugin
Plugin "replace" can't be imported
Adding en_US.UTF-8 to language list
Config time: 0.080
Loading mirror speeds from cached hostfile
 * epel: dfw.mirror.rackspace.com
ius                                                                                                                                                                                             | 1.3 kB  00:00:00
ius/x86_64/primary                                                                                                                                                                              | 108 kB  00:00:00
repo time: 0.573
Setting up Package Sacks
pkgsack time: 0.373
rpmdb time: 0.000
warning: /var/repo/ius/7/x86_64/packages/a/apr15u-devel-1.5.2-2.ius.el7.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID 4b274df2: NOKEY
Public key for apr15u-devel-1.5.2-2.ius.el7.x86_64.rpm is not installed
(1/387): apr15u-devel-1.5.2-2.ius.el7.x86_64.rpm                                                                                                                                                | 194 kB  00:00:00
(2/387): apr15u-1.5.2-2.ius.el7.x86_64.rpm                                                                                                                                                      | 112 kB  00:00:00
. . . 
(385/387): uwsgi-plugin-python36u-2.0.17.1-1.ius.el7.x86_64.rpm                                                                                                                                 |  63 kB  00:00:00
(386/387): yum-plugin-replace-0.2.7-1.ius.el7.noarch.rpm                                                                                                                                        |  15 kB  00:00:00
(387/387): redis5-5.0.5-2.el7.ius.x86_64.rpm                                                                                                                                                    | 902 kB  00:00:00
Removing apr15u-1.5.2-2.ius.el7.x86_64.rpm, due to missing GPG key.
Removing apr15u-devel-1.5.2-2.ius.el7.x86_64.rpm, due to missing GPG key.
. . . 
Removing uwsgi-plugin-python35u-2.0.17.1-1.ius.el7.x86_64.rpm, due to missing GPG key.
Removing uwsgi-plugin-python36u-2.0.17.1-1.ius.el7.x86_64.rpm, due to missing GPG key.
Removing yum-plugin-replace-0.2.7-1.ius.el7.noarch.rpm, due to missing GPG key. `

The `ius-release` packacge is installed, including the `RPM-GPG-KEY-IUS-7` and accessing `https://repo.ius.io/7/$basearch/`.

I can complete the download by not performing the GPG package check (the '-g' switch for reposync) but I don;t like the security implications.

Is this a problem with the IUS repo?

**Comment by survient** [comment]
I was able to successfully replicate this issue using a freshly kicked CentOS 7 server, the only extra step I had to add to resolve the issue was to manually import the new IUS GPG key:

`rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-IUS-7`

After this a reposync command completed successfully:

```
reposync -g -l -p /mnt/testius/var/repo/ius/7/x86_64 --norepopath -m --download-metadata -r ius
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.dal.nexril.net
 * epel: mirror.dal.nexril.net
 * extras: mirror.dal.nexril.net
 * updates: mirror.dal.nexril.net
(1/387): apr15u-devel-1.5.2-2.ius.el7.x86_64.rpm                                                                                                                       | 194 kB  00:00:00     
(2/387): apr15u-1.5.2-2.ius.el7.x86_64.rpm                                                                                                                             | 112 kB  00:00:00     
(3/387): apr15u-util-1.5.4-3.ius.el7.x86_64.rpm
```

**Comment by carlwgeorge** [comment]
@philtech-oh Make sure to clear your yum cache as well after you import the new key.  If you're curious, more details on the new key and infrastructure changes can be [found here](https://github.com/iusrepo/infrastructure/issues/14).

**Comment by philtech-oh** [comment]
Thanks for the help!  The manual GPG key import worked.
