### ISSUE TITLE
Rackspace Mirrors Failing - URL change

### ISSUE THREAD

**Issue by tdownie** [iuscommunity/infrastructure#18]
Tried to run `yum update` on one of our servers today and the IUS repo (IUS Community Packages for Enterprise Linux 7 - x86_64) failed and I got 404s for every mirror it tried:

http://iad.mirror.rackspace.com/ius/stable/CentOS/7/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
http://lon.mirror.rackspace.com/ius/stable/CentOS/7/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
http://ord.mirror.rackspace.com/ius/stable/CentOS/7/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
http://hkg.mirror.rackspace.com/ius/stable/CentOS/7/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
http://syd.mirror.rackspace.com/ius/stable/CentOS/7/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.

Those also fail if I try to go to them via the browser. 

I took a look at `/etc/yum.repos.d/ius.repo` and the mirror list is pointing here:
https://mirrors.iuscommunity.org/mirrorlist?repo=ius-centos7&arch=x86_64&protocol=http

But the rackspace mirror urls listed all give 404s.

It looks like the paths changed. This gives a 404 because `stable/` doesn't exist from what I'm seeing.
http://iad.mirror.rackspace.com/ius/stable/CentOS/7/x86_64/

This looks like it's valid though:
http://iad.mirror.rackspace.com/ius/7/x86_64/

(Also sent this via email to dev@ius.io until I realized this infra repo existed)

**Comment by carlwgeorge** [comment]
As detailed in #14, you need to upgrade your ius-release package to version 2.  If you have already done that, check if you have any rpmnew files in `/etc/yum.repos.d/` and merge them.

**Comment by tdownie** [comment]
Thank you! All set now after updating the release pkg
