### ISSUE TITLE
yum-plugin-replace download issue

### ISSUE THREAD

**Issue by arnebjarne** [iuscommunity/infrastructure#20]
Hi IUS Team.

We mirror your repos via repo.ius.io/7/x86_64/ and repo.ius.io/6/x86_64/ every night.

Every day we get reports that yum-plugin-replace have changed

it bounces back and forth with
``
`` + yum-plugin-replace-0.2.7-1.ius.el6.noarch.rpm (5050 kiB)
`` - yum-plugin-replace-0.2.7-1.ius.el6.noarch.rpm (4870 kiB)
``

notice the file sizes.

Is one of your load balancers out of sync or is your build system?

BR,
Bjarne, Sinch Denmark

**Comment by carlwgeorge** [comment]
That file hasn't changed in a long time.  I checked the load balancer nodes and they all have the same identical file, verified by checksum.

```
5719470f4f830eb3148cac264b68e66c45ce098c7af6ada352133e06228c86fd  6/x86_64/packages/y/yum-plugin-replace-0.2.7-1.ius.el6.noarch.rpm
```

This matches the checksum in the [repodata XML file](https://repo.ius.io/6/x86_64/repodata/primary.xml.gz).

```xml
<name>yum-plugin-replace</name>
<arch>noarch</arch>
<version epoch="0" ver="0.2.7" rel="1.ius.el6"/>
<checksum type="sha256" pkgid="YES">5719470f4f830eb3148cac264b68e66c45ce098c7af6ada352133e06228c86fd</checksum>
```


It's possible the file was corrupted on a CDN node you're hitting.  I forced a content refresh on the CDN to hopefully fix this.  If you want to bypass the CDN and sync from the same source the CDN uses, follow the [instructions in the FAQ](https://ius.io/faq#can-i-become-an-ius-mirror).
