### ISSUE TITLE
14: PYCURL ERROR 6 - "Couldn't resolve host 'mirrors.iuscommunity.org'"

### ISSUE THREAD

**Issue by slrslr** [iuscommunity/infrastructure#21]
Hello,
please what is alternative mirrorlist= URL for mirrors.iuscommunity.org as this host can not be resolved per the yum output in this issue title?

```
# grep -i ius /etc/yum.repos.d/mratwork.repo
[mratwork-ius-stable]
name=MRatWork - IUS Community Packages for EL $releasever (stable) - arch
baseurl=http://dl.iuscommunity.org/pub/ius/stable/CentOS/$releasever/$basearch
mirrorlist=http://mirrors.iuscommunity.org/mirrorlist/?repo=ius-centos$releasever&arch=$basearch&protocol=http
[mratwork-ius-archive]
name=MRatWork - IUS Community Packages for EL $releasever (archive) - arch
baseurl=http://dl.iuscommunity.org/pub/ius/archive/CentOS/$releasever/$basearch
mirrorlist=http://mirrors.iuscommunity.org/mirrorlist?repo=ius-centos$releasever-archive&arch=$basearch&protocol=http
[mratwork-ius-testing]
name=MRatWork - IUS Community Packages for EL $releasever (testing) - arch
baseurl=http://dl.iuscommunity.org/pub/ius/testing/CentOS/$releasever/$basearch
mirrorlist=http://mirrors.iuscommunity.org/mirrorlist?repo=ius-centos$releasever-testing&arch=$basearch&protocol=http
```

also it can not resolve varnish:
`http://repo.varnish-cache.org/redhat/varnish-3.0/el6/i386/repodata/repomd.xml: [Errno 14] PYCURL ERROR 6 - "Couldn't resolve host 'repo.varnish-cache.org'"`

**Comment by carlwgeorge** [comment]
The IUS mirrorlist service was [turned off over a year ago](https://github.com/iusrepo/infrastructure/issues/14#issuecomment-572276277) as part of our move a [CDN](https://github.com/iusrepo/infrastructure/issues/14).  If you were using ius-release this transition would have been seamless.

I don't know what MRatWork is.  Perhaps you should report the issue to them.

This is also the wrong place to report issues with the varnish repo.

**Comment by slrslr** [comment]
So i should comment out (prefix by "#" character) the "mirrorlist=" lines that contains mirrors.iuscommunity URL as there is no replacement?

**Comment by jeffsheltren** [comment]
Generally you're best off installing the ius-release package to handle the yum config file(s) so that you'll keep up with any updates in the future. If you want to configure the repo manually, you can see the files used by ius-release here: https://github.com/iusrepo/ius-release
