### ISSUE TITLE
HELP!  Your YUM repo certificate has expired!!

### ISSUE THREAD

**Issue by santoch** [iuscommunity/infrastructure#22]
https://dl.iuscommunity.org/pub/ius/stable/CentOS7/x86+64/repodata/repomd.xml: [Errno 14] curl#60 - "Peer's Certificate has expired."

PLEASE update your yum repo certificate!

**Comment by JayBazuzi** [comment]
It expired 18 March 2021.

**Comment by survient** [comment]
The publish URL for the IUS repo changed several months back, if you check the current repo files per https://ius.io/setup at
https://repo.ius.io/ius-7.repo
```
[ius]
name = IUS for Enterprise Linux 7 - $basearch
baseurl = https://repo.ius.io/7/$basearch/
enabled = 1
repo_gpgcheck = 0
gpgcheck = 1
gpgkey = https://repo.ius.io/RPM-GPG-KEY-IUS-7

[ius-debuginfo]
name = IUS for Enterprise Linux 7 - $basearch - Debug
baseurl = https://repo.ius.io/7/$basearch/debug/
enabled = 0
repo_gpgcheck = 0
gpgcheck = 1
gpgkey = https://repo.ius.io/RPM-GPG-KEY-IUS-7

[ius-source]
name = IUS for Enterprise Linux 7 - Source
baseurl = https://repo.ius.io/7/src/
enabled = 0
repo_gpgcheck = 0
gpgcheck = 1
gpgkey = https://repo.ius.io/RPM-GPG-KEY-IUS-7
```
which is not using an expired TLS cert.

**Comment by carlwgeorge** [comment]
The [switch to a CDN](https://github.com/iusrepo/announce/issues/13) was announced almost two years ago.  The dl.iuscommunity.org domain still exists for convenience but you shouldn't rely on it, as you can see that it isn't as well maintained.  Regardless, I've force refreshed the LetsEncrypt automation to renew that certificate.  You should expect that domain to go away at some point in the future.

**Comment by carlwgeorge** [comment]
FYI https://github.com/iusrepo/announce/issues/26
