### ISSUE TITLE
Centos 6 IUS 

### ISSUE THREAD

**Issue by octachrome** [iuscommunity/infrastructure#24]
Is the Centos/RHEL 6 IUS RPM still hosted anywhere? I can only find references to the following URLs, and they are both broken:

- https://repo.ius.io/ius-release-el6.rpm
- https://centos6.iuscommunity.org/ius-release.rpm

**Comment by carlwgeorge** [comment]
See https://github.com/iusrepo/announce/issues/24.

If you see links to anything about EL6 on our website, please file an issue or open a pull request on https://github.com/iusrepo/iusrepo.github.io so we can remove it.

**Comment by octachrome** [comment]
It would be very helpful if the website mentioned https://vault.ius.io/ somewhere for those of us who rely on old versions. Would you accept a PR for an FAQ entry covering this?

Is the list of supported centos versions listed anywhere on the website?

**Comment by carlwgeorge** [comment]
I'd be happy to review and merge a PR to add more [FAQ entries](https://ius.io/faq) ([source](https://github.com/iusrepo/iusrepo.github.io/blob/main/markdown/faq.md)), such as to mention vault.ius.io, as long as the wording is clear that packages on vault.ius.io are completely unmaintained and should not be used.  They are only there for historical purposes.  You should not be relying on unmaintained packages, or EOL operating systems for that matter.  I'm not interested in hearing your reasons about why you think it's ok in your scenario or that you're being forced to do it.  It's irresponsible and I hope you are able to upgrade to ASAP.

The [setup page](https://ius.io/setup) ([source](https://github.com/iusrepo/iusrepo.github.io/blob/main/markdown/setup.md)) only includes instructions for EL7.  There is also an [FAQ entry about the lack of EL8 packages](https://ius.io/faq#why-doesnt-ius-have-packages-for-rhel-8).
