### ISSUE TITLE
Metadata file does not match checksum

### ISSUE THREAD

**Issue by prupert** [iuscommunity/infrastructure#25]
There appears to be an issue with the metadata file in the yum repository rendering the IUS yum repository unusable. 

```
https://repo.ius.io/7/x86_64/repodata/primary.xml.gz: [Errno -1] Metadata file does not match checksum
Trying other mirror.
```

The issue persists after full cleanup (`yum clean all; rm -rf /var/cache/yum/*`).

**Comment by jeffsheltren** [comment]
I was able to purge the CDN cache this morning, and yum updates against the main repo are working fine for me now. @prupert can you please confirm it's working for you again?

**Comment by prupert** [comment]
Yes, I have not seen any more issues from our end with the `ius` yum repo.
