### ISSUE TITLE
primary.xml.gz Metadata file does not match checksum

### ISSUE THREAD

**Issue by yeukhon** [iuscommunity/infrastructure#27]
I am getting this trying to build new CentOS 7 image at work and I am getting this:

```
#8 9.150 https://repo.ius.io/7/x86_64/repodata/primary.xml.gz: [Errno -1] Metadata file does not match checksum
#8 9.151 Trying other mirror.
#8 19.75 https://repo.ius.io/7/x86_64/repodata/primary.xml.gz: [Errno -1] Metadata file does not match checksum
#8 19.75 Trying other mirror.
```

I checked

```
wget https://repo.ius.io/7/x86_64/repodata/primary.xml.gz
cat primary.xml.gz | shasum -a 256
```
On Mac the checksum is `32dfb5a943e20746ba730338963e9aa062af36fb977cbcd3ea21d07998a3ca78` but repomd.xml is showing a different checksum.
```
<data type="primary">
<checksum type="sha256">c04a6c1964165a4741a457e58b6a0843d70656811634b214da0ea5fef278eca0</checksum>
<open-checksum type="sha256">0de55a8cb81882d6955b3838c378dbf1146652efba8bd8aa5b0bb42243d22dd3</open-checksum>
<location href="repodata/primary.xml.gz"/>
<timestamp>1652208144</timestamp>
<size>86092</size>
<open-size>976384</open-size>
</data>
```

It was updated today at 12:59 Eastern.

**Comment by yeukhon** [comment]
The timestamp clearly marks:

`Tuesday, May 10, 2022 2:42:24 PM [GMT-04:00](https://www.epochconverter.com/timezones?q=1652208144) DST`
Seems like the xml file did not actually get updated despite the file was rewritten? The LM date is 05/17/2022, 12:59:45 PM

**Comment by yeukhon** [comment]
Maybe we need to purge CDN again?
https://github.com/iusrepo/infrastructure/issues/25

**Comment by carlwgeorge** [comment]
Earlier I was promoting a package from the testing repo to the main repo, as well as moving some old content from the main repo to the archive repo.  This caused the repodata to change.  I sent the API calls to refresh the content, but it seems it took longer than normal to take effect.  It looks like it has finished refreshing now.

```
[carl@teal:~]$ curl -s https://origin.repo.ius.io/7/x86_64/repodata/primary.xml.gz | shasum -a 256
3e7b96f2bc27123bac843df2477198e6253bc226692d3de8375fc575b8340dd4  -
[carl@teal:~]$ curl -s https://repo.ius.io/7/x86_64/repodata/primary.xml.gz | shasum -a 256
3e7b96f2bc27123bac843df2477198e6253bc226692d3de8375fc575b8340dd4  -
```

```
[carl@teal:~]$ curl -s https://origin.repo.ius.io/7/x86_64/repodata/primary.xml.gz | zcat | grep -Po 'packages="[0-9]+"'
packages="247"
[carl@teal:~]$ curl -s https://repo.ius.io/7/x86_64/repodata/primary.xml.gz | zcat | grep -Po 'packages="[0-9]+"'
packages="247"
```
