### ISSUE TITLE
You can't subscribe to announce repo issues via RSS, but you can subscribe to Releases.

### ISSUE THREAD

**Issue by jordanconway** [iuscommunity/infrastructure#28]
Hello,
Please consider publishing "Releases" in this repo for each announcement, as there is no way to subscribe to Issues of a Github project outside of being an actual user.
The releases page however features an atom feed that can be subscribed to and then piped into Slack, Mattermost etc which would be very helpful in tracking these issues as a group
https://github.com/iusrepo/announce/releases.atom can be subscribed to and I believe may be easy to integrate into your Announcement Issue creation process.
Thank you!

**Comment by carlwgeorge** [comment]
I transferred this out of the https://github.com/iusrepo/announce repo to avoid sending notifications to people who have subscribed to that repo for it's intended purpose (important announcements).

Releases don't really fit our needs.  Each release needs a tag, and tagging the same commit over and over doesn't make sense.  Another problem would be the separation of initial announcement (creating an issue to announce a package retirement) and the actual action (closing the issue to indicate the package has been retired).  I'm not sure how that would even work as a release.

I'm not interested in changing the IUS announce process at this time.  A web search of "github issues to rss feed" returns lots of potential solutions if you want to set this up for yourself or your organization.

**Comment by jordanconway** [comment]
Thanks for the consideration and explanation - I did indeed find a middleman solution.
