### ISSUE TITLE
IUS should sign the repos metadata file

### ISSUE THREAD

**Issue by glisha** [iuscommunity/infrastructure#4]
At the moment the IUS packages are signed, but the repomd.xml file is not signed. 

The IUS repos are missing the repomd.xml.asc signed repo metadata that yum checks when repo_gpgcheck is enabled. 

A malicious attacker can register a mirror and change the repomd.xml files on the mirror to deploy malicious packages in the name of the IUS community.

Please sign the repomd.xml.

https://access.redhat.com/blogs/766093/posts/1976693
https://lists.centos.org/pipermail/centos/2015-May/152063.html
https://blog.packagecloud.io/eng/2014/11/24/howto-gpg-sign-verify-rpm-packages-yum-repositories/

**Comment by b-harper** [comment]
Hey @glisha,

Thanks for taking the time to contact us about this issue.  There are some similar concerns raised in iuscommunity-pkg/ius-release#3.  In general, I am a fan of using more security than less security.  

Looking over CentOS and EPEL repository configuration files, they do not have any reference to ```repo_gpgcheck``` and use the default, disable.  CentOS does provide signed repodata, but EPEL does not.  It is not clear why theses projects are configured this way.  If these projects do not feel signed metadata is needed, should a third party repository?

While the command to sign the metadata is fairly straight forward, incorporating it into our currently automation unfortunately will not be straight forward.  Also, we are looking to overhaul that automation along with several other back end systems.  It is a tough call to make changes to automation we are looking to replace.  While we determine how to proceed, you could use our [master mirror][0] or create your own private [mirror][1] if you are concerned using the mirror pool. 

> A malicious attacker can register a mirror and change the repomd.xml files on the mirror to deploy malicious packages in the name of the IUS community.

Wouldn't an attacker still need to compromise our GPG key to sign those malicious packages?  


[0]: https://dl.iuscommunity.org/pub/ius/
[1]: https://ius.io/Mirrors/

**Comment by b-harper** [comment]
Looking at the Fedora mirrors, they do not have signed metadata either.

**Comment by glisha** [comment]
Yes, Centos/RHEL don't enable repo_gpgcheck by default. RHEL probably because they don't use public mirrors, Centos because the configuration shouldn't be different than RHEL.

But the latest [STIG for RHEL 7](https://static.open-scap.org/ssg-guides/ssg-centos7-guide-stig-rhel7-server-upstream.html#xccdf_org.ssgproject.content_rule_ensure_gpgcheck_repo_metadata) says it should be enabled.

For attacks on metadata this are good reads [FAQ](https://www2.cs.arizona.edu/stork/packagemanagersecurity/faq.html) and [Other attacks](https://www2.cs.arizona.edu/stork/packagemanagersecurity/otherattacks.html).

As for why doesn't EPEL sign the metadata, I will check, I couldn't find any discussion in their mailing lists. 

And since IUS depends on EPEL it doesn't make sense to sign IUS metadata before (if ever) EPEL signs it. So I will close the issue. :)

**Comment by b-harper** [comment]
@glisha, thanks for sharing those links, there is some good stuff in there.  

The open-scap.org site seems overly complicated to use.  I am attempting to determine what (if any) recommendations there are for other RPM based distributions regarding singed repodata, but I am struggling to find the correct documents.  The mis-configuration of SSL is disappointing for a site about security audits.  The STIG for RHEL 7 states that it is a draft status, I am curious what changes might comes when it get finalized. 

Please let us know if you are able to track down any information regarding EPEL.
