### ISSUE TITLE
Disable pcre JIT compilation by default

### ISSUE THREAD

**Issue by immanetize** [iuscommunity/infrastructure#5]
Hello IUS team, I'm working on SELinux confinement of some PHP applications and was seeing denial AVCs like this:

    type=AVC msg=audit(1501553849.780:162): avc:  denied  { execmem } for  pid=2662 comm="php-fpm" scontext=system_u:system_r:httpd_t:s0 tcontext=system_u:system_r:httpd_t:s0 tclass=process

I did some research and found https://bugs.exim.org/show_bug.cgi?id=1749 and https://bugzilla.redhat.com/show_bug.cgi?id=1398474, which suggested PCRE just-in-time compilation was responsible, and found that setting `pcre.jit=0` does stop these AVCs for my use case.

I'm on php70u (php70u-common-7.0.21-1.ius.el7.x86_64) but it looks like this would apply to php71u as well.  What do you think about `pcre.jit=0` as the default?

**Comment by carlwgeorge** [comment]
Hey Pete.  I opened separate issues on the specific package source repos to track fixing this.
