### ISSUE TITLE
Pypy3 rpm

### ISSUE THREAD

**Issue by mosquito** [iuscommunity/infrastructure#6]
Hi there. I prepare pypy3 spec and patches [here](https://github.com/mosquito/pypy3)

**Comment by carlwgeorge** [comment]
Hello @mosquito.  New packages requests should be submitted to our [wishlist](https://github.com/iuscommunity/wishlist/blob/master/CONTRIBUTING.md).

However, in this case I can already tell you that this package isn't a good fit for IUS.  We specifically provide only newer versions of stock packages.  pypy3 is not in the base RHEL operating system, so it is a better candidate for EPEL.  In fact, all you have to do is ask the Fedora maintainer to create an EPEL7 branch.

**Comment by mosquito** [comment]
In EPEL pypy is python2 build. pypy3 is the same but python 3.5 build.

**Comment by carlwgeorge** [comment]
EPEL package sources are branches in Fedora's dist-git.  pypy and pypy3 are separate repos.

* https://src.fedoraproject.org/rpms/pypy
* https://src.fedoraproject.org/rpms/pypy3

pypy has EPEL6 and EPEL7 branches, but pypy3 does not.  The most appropriate path forward is to request the Fedora pypy3 package maintainer to create an EPEL7 branch.
