### ISSUE TITLE
IUS Repo on IPv6

### ISSUE THREAD

**Issue by Gunni** [iuscommunity/infrastructure#7]
The IUS repo reports a AAAA record over DNS when queried, and accepts the connection, and the https handshake succeeds, but after that, nothing.

Additionally i have expirienced in some unacceptable timeout limits in applications such as CURL or YUM.

Example:
```
# time curl -v6 --head https://centos7.iuscommunity.org/ius-release.rpm                                                                                                      35 ↵
* About to connect() to centos7.iuscommunity.org port 443 (#0)
*   Trying 2001:4802:7801:102:be76:4eff:fe21:14aa...
* Connected to centos7.iuscommunity.org (2001:4802:7801:102:be76:4eff:fe21:14aa) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* NSS error -5961 (PR_CONNECT_RESET_ERROR)
* TCP connection reset by peer
* Closing connection 0
curl: (35) TCP connection reset by peer

0.19s user 0.14s system 0% cpu 3:21.60 total
```

**Comment by carlwgeorge** [comment]
The same command is working fine for me.

<details>
<summary>output</summary>

```
$ time curl -v6 --head https://centos7.iuscommunity.org/ius-release.rpm
*   Trying 2001:4802:7801:102:be76:4eff:fe21:14aa...
* TCP_NODELAY set
* Connected to centos7.iuscommunity.org (2001:4802:7801:102:be76:4eff:fe21:14aa) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: none
  CApath: none
* loaded libnssckbi.so
* ALPN/NPN, server did not agree to a protocol
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=*.iuscommunity.org,OU=RPM Development,O="Rackspace US, Inc.",L=San Antonio,ST=Texas,C=US
* 	start date: Jul 24 00:00:00 2017 GMT
* 	expire date: May 08 23:59:59 2018 GMT
* 	common name: *.iuscommunity.org
* 	issuer: CN=thawte SSL CA - G2,O="thawte, Inc.",C=US
> HEAD /ius-release.rpm HTTP/1.1
> Host: centos7.iuscommunity.org
> User-Agent: curl/7.53.1
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
HTTP/1.1 301 Moved Permanently
< Date: Tue, 14 Nov 2017 23:49:45 GMT
Date: Tue, 14 Nov 2017 23:49:45 GMT
< Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
< Location: https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/ius-release-1.0-15.ius.centos7.noarch.rpm
Location: https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/ius-release-1.0-15.ius.centos7.noarch.rpm
< Content-Type: text/html; charset=iso-8859-1
Content-Type: text/html; charset=iso-8859-1

< 
* Connection #0 to host centos7.iuscommunity.org left intact

real	0m0.517s
user	0m0.082s
sys	0m0.016s
```

</details>

Can you try from other locations and see if the problem is limited to one particular location?

**Comment by oogali** [comment]
Works for me with my provider-assigned IPv6 addressing.

```
time curl -v6 --head https://centos7.iuscommunity.org/ius-release.rpm
*   Trying 2001:4802:7801:102:be76:4eff:fe21:14aa...
* TCP_NODELAY set
* Connected to centos7.iuscommunity.org (2001:4802:7801:102:be76:4eff:fe21:14aa) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=Texas; L=San Antonio; O=Rackspace US, Inc.; OU=RPM Development; CN=*.iuscommunity.org
*  start date: Jul 24 00:00:00 2017 GMT
*  expire date: May  8 23:59:59 2018 GMT
*  subjectAltName: host "centos7.iuscommunity.org" matched cert's "*.iuscommunity.org"
*  issuer: C=US; O=thawte, Inc.; CN=thawte SSL CA - G2
*  SSL certificate verify ok.
> HEAD /ius-release.rpm HTTP/1.1
> Host: centos7.iuscommunity.org
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
HTTP/1.1 301 Moved Permanently
< Date: Thu, 16 Nov 2017 14:42:59 GMT
Date: Thu, 16 Nov 2017 14:42:59 GMT
< Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
< Location: https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/ius-release-1.0-15.ius.centos7.noarch.rpm
Location: https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/ius-release-1.0-15.ius.centos7.noarch.rpm
< Content-Type: text/html; charset=iso-8859-1
Content-Type: text/html; charset=iso-8859-1

<
* Connection #0 to host centos7.iuscommunity.org left intact

real	0m0.340s
user	0m0.026s
sys	0m0.012s
```

**Comment by oogali** [comment]
@Gunni Your connectivity seems to be working, but based on the error message, the NSS crypto library on your system is having trouble performing the handshake.

This may be limited to your system.

Can you provide the output of `curl --version`? And perhaps try from a system with a newer version of NSS (or even OpenSSL)?

```
$ curl --version
curl 7.54.0 (x86_64-apple-darwin17.0) libcurl/7.54.0 LibreSSL/2.0.20 zlib/1.2.11 nghttp2/1.24.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy
```

**Comment by carlwgeorge** [comment]
For reference, here is the same output from a CentOS 7 system (where I presume @Gunni is running the command from):

```
$ curl --version
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.28.4 zlib/1.2.7 libidn/1.28 libssh2/1.4.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets
```

**Comment by Gunni** [comment]
@oogali i am running it on a Centos 7 system.

I updated it 2 days ago, i think i forgot to check after the update, i'll do it once i get there later today, assuming I remember to.

Edit: i have checked and my curl version seems to match the one @carlwgeorge sent.

Additionally i have OpenSSL 1.0.2k-fips  26 Jan 2017

	# wget -vd https://centos7.iuscommunity.org/ius-release.rpm
	DEBUG output created by Wget 1.14 on linux-gnu.

	URI encoding = ‘UTF-8’
	Converted file name 'ius-release.rpm' (UTF-8) -> 'ius-release.rpm' (UTF-8)
	Converted file name 'ius-release.rpm' (UTF-8) -> 'ius-release.rpm' (UTF-8)
	--2017-11-16 23:07:51--  https://centos7.iuscommunity.org/ius-release.rpm
	Resolving centos7.iuscommunity.org (centos7.iuscommunity.org)... 2001:4802:7801:102:be76:4eff:fe21:14aa, 162.242.221.48
	Caching centos7.iuscommunity.org => 2001:4802:7801:102:be76:4eff:fe21:14aa 162.242.221.48
	Connecting to centos7.iuscommunity.org (centos7.iuscommunity.org)|2001:4802:7801:102:be76:4eff:fe21:14aa|:443... connected.
	Created socket 3.
	Releasing 0x0000000001e7c910 (new refcount 1).
	Initiating SSL handshake.
	SSL handshake timed out.
	Closed fd 3
	Unable to establish SSL connection.

Note that it stayed at "Initiating SSL handshake" for almost exactly 15 minutes (0.06s user 0.05s system 0% cpu 15:00.34 total).

And now 4

	# wget -4vd https://centos7.iuscommunity.org/ius-release.rpm
	DEBUG output created by Wget 1.14 on linux-gnu.

	URI encoding = ‘UTF-8’
	Converted file name 'ius-release.rpm' (UTF-8) -> 'ius-release.rpm' (UTF-8)
	Converted file name 'ius-release.rpm' (UTF-8) -> 'ius-release.rpm' (UTF-8)
	--2017-11-16 23:59:00--  https://centos7.iuscommunity.org/ius-release.rpm
	Resolving centos7.iuscommunity.org (centos7.iuscommunity.org)... 162.242.221.48
	Caching centos7.iuscommunity.org => 162.242.221.48
	Connecting to centos7.iuscommunity.org (centos7.iuscommunity.org)|162.242.221.48|:443... connected.
	Created socket 3.
	Releasing 0x000000000085d740 (new refcount 1).
	Initiating SSL handshake.
	Handshake successful; connected socket 3 to SSL handle 0x0000000000888830
	...<CUT>...
	Saving to: ‘ius-release.rpm.1’

	100%[===============================================================================================================================================>] 8,340       --.-K/s   in 0s

	2017-11-16 23:59:03 (62.1 MB/s) - ‘ius-release.rpm.1’ saved [8340/8340]

**Comment by b-harper** [comment]
@Gunni,

Let take a step back and verify some basics.  

Are you only having this issue on a single server?
Are you having HTTPS/IPV6 issues with other sites?
Has that URL ever worked via HTTPS/IPV6?  If so, did it stop working around the time you submitted this issue?
Can you download the file via the [full url][0]?

[0]: https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/ius-release-1.0-15.ius.centos7.noarch.rpm

**Comment by Gunni** [comment]
@b-harper, only one server here, this is my home network monitoring server.

IPv6 works fine for everything else that i have tried, and i'm using it too on my desktop.

The URL works fine from my desktop and over IPv4 on the server.

The URL used to work, but that was before i setup an IPv6 tunnel over IPv4 to my workplace, its MTU is limited to 1476 if that matters.

**Comment by oogali** [comment]
Are you sure your MTU is correct? The symptoms you're describing (works fine on IPv4, hangs at handshake on IPv6) is emblematic of a MTU problem -- specifically, the remote router handling your tunneling is dropping the packet as it's too big for your tunneled interface.

1476 is a common MTU used when tunneling traffic over GRE (as the GRE packet header is 24 bytes).

If you're not going over a GRE tunnel (e.g. using another tunnel protocol, or say OpenVPN), then you may need to allow for additional headroom by further decreasing your MTU.

EDIT: If you're experiencing that problem here on a SSL handshake, then you're likely going to have issues on other IPv6 sites when you attempt to download large objects.

**Comment by b-harper** [comment]
@Gunni,

Sounds like it might be your tunnel.  It has been about five years since I have messed with IPV6->IPv4 tunnels, so I am not sure how much I might be able to help.  Thanks to @oogali for filling in that gap.

>If you're experiencing that problem here on a SSL handshake, then you're likely going to have issues on other IPv6 sites when you attempt to download large objects.

Note, the issue is will a short URL that is just a 301 to a long URL for the ius-release RPM.  Can you download the file via the [long url][0]? 

[0]: https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/ius-release-1.0-15.ius.centos7.noarch.rpm

**Comment by Gunni** [comment]
@oogali It seems you are correct, i advertised the correct MTU via router advertisement but since this server has a static IP, i forgot to manually tune the mtu.

Setting the MTU with `ip link set dev enp2s0 mtu 1476` made the download work right away!

> 2017-11-21 20:29:06 (32.6 MB/s) - ‘ius-release-1.0-15.ius.centos7.noarch.rpm’ saved [8340/8340]

Thanks for the help, my bad.

@b-harper in my last post i was using your full url, i just forgot to say so.

**Comment by b-harper** [comment]
@Gunni, glad to hear this issue has been resolved.

@oogali, thanks for your help.
