### ISSUE TITLE
Certificate has expired: *.iuscommunity.org

### ISSUE THREAD

**Issue by rcaught** [iuscommunity/infrastructure#8]
<img width="779" alt="screen shot 2018-05-09 at 12 38 25 pm" src="https://user-images.githubusercontent.com/144163/39792819-e7ce4d48-5385-11e8-9106-cd509ce9a86c.png">

**Comment by carlwgeorge** [comment]
Thanks for reporting this.  That url redirect lives on a different server, and I forgot about it when I was rotating the cert last month.  It's fixed now.
